declare const _default: {
    ascii: RegExp;
    decimal: RegExp;
    digit: RegExp;
    domain: RegExp;
    email: RegExp;
    hexColor: RegExp;
    hsl: RegExp;
    hsla: RegExp;
    integer: RegExp;
    ipv4: RegExp;
    ipv6: RegExp;
    isAscii: (string: string) => boolean;
    isDecimal: (string: string) => boolean;
    isDigit: (string: string) => boolean;
    isDomain: (string: string) => boolean;
    isEmail: (string: string) => boolean;
    isHexColor: (string: string) => boolean;
    isHsl: (string: string) => boolean;
    isHsla: (string: string) => boolean;
    isInteger: (string: string) => boolean;
    isIP: (string: string) => boolean;
    isIPv4: (string: string) => boolean;
    isIPv6: (string: string) => boolean;
    isQQ: (string: string) => boolean;
    isRealNumber: (string: string) => boolean;
    isRgb: (string: string) => boolean;
    isRgba: (string: string) => boolean;
    qq: RegExp;
    realNumber: RegExp;
    rgb: RegExp;
    rgba: RegExp;
};
export default _default;
