import clientX from './clientX';
import clientY from './clientY';
import createEvent from './createEvent';
import domReady from './domReady';
import insertScript from './insertScript';
import isElement from './isElement';
import isInViewport from './isInViewport';
import isWindow from './isWindow';
import pageX from './pageX';
import pageY from './pageY';
import scrollTo from './scrollTo';
import scrollX from './scrollX';
import scrollY from './scrollY';
import viewport from './viewport';
declare const _default: {
    clientX: typeof clientX;
    clientY: typeof clientY;
    createEvent: typeof createEvent;
    domReady: typeof domReady;
    insertScript: typeof insertScript;
    isElement: typeof isElement;
    isInViewport: typeof isInViewport;
    isWindow: typeof isWindow;
    pageX: typeof pageX;
    pageY: typeof pageY;
    scrollTo: typeof scrollTo;
    scrollX: typeof scrollX;
    scrollY: typeof scrollY;
    viewport: typeof viewport;
};
export default _default;
